export declare const PI: number;
export declare const _2PI: number;
export declare const _2_3PI: number;
export declare const PITAU: number;
export declare const INFINITY: number;
export declare const RAD_PER_DEG: number;
export declare const HALF_PI: number;
export declare const QUARTER_PI: number;
export declare const TWO_THIRDS_PI: number;
export declare const _360 = 360;
export declare function H_pow($num: number, $pow?: number): number;
export declare function H_ceil($num: number): number;
export declare function H_floor($num: number): number;
export declare function H_sin($angle: number): number;
export declare function H_sqrt($num: number): number;
export declare function H_abs($num: number): number;
export declare function _isBetween($num: any, $1: any, $2: any): boolean;
export declare function _limit($arr?: never[]): {
    max: number;
    min: number;
};
export declare function _isEdge($location: any, $edge: any): boolean;
